-- Credits to @Taylor Starr
SELECT DISTINCT
CASE
    WHEN SPLIT_PART(GHP.FILEDATE, '_', 1) >= SUBSTR(HRA.DECISIONTIMESTAMP, 6, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 9, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 1, 4) THEN 'SUCCESSFULLY SENT'
    WHEN SPLIT_PART(GHP.FILEDATE, '_', 1) < SUBSTR(HRA.DECISIONTIMESTAMP, 6, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 9, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 1, 4) THEN 'UPDATE FAILED TO SEND'
    WHEN MAXGHP.MAXFILE IS NULL THEN 'FAILED TO SEND'
    ELSE 'TEST'
    END AS "Identified File Failure",
PAT.MEMBERID AS "Member ID", 
HRA.AUTHNUMBER AS "Auth Number", 
HRA.AUTHSTATUS AS "Auth Status", 
HRA.VERSION AS "Auth Version", 
SUBSTR(HRA.DATECREATED, 6, 2) || '/' ||SUBSTR(HRA.DATECREATED, 9, 2) || '/' ||SUBSTR(HRA.DATECREATED, 1, 4) AS "Created Date",
SUBSTR(HRA.DATECREATED, 12, 5) AS "Created Time",
SUBSTR(HRA.LASTUPDATED, 6, 2) || '/' ||SUBSTR(HRA.LASTUPDATED, 9, 2) || '/' ||SUBSTR(HRA.LASTUPDATED, 1, 4) AS "Updated Date",
SUBSTR(HRA.LASTUPDATED, 12, 5) AS "Updated Time",
SUBSTR(HRA.DECISIONTIMESTAMP, 6, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 9, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 1, 4) AS "Decision Date",
SUBSTR(HRA.DECISIONTIMESTAMP, 12, 5) AS "Decision Time",
SPLIT_PART(GHP.FILEDATE, '_', 1) AS "Last GHP File Date", 
SPLIT_PART(GHP.FILEDATE, '_', 2) AS "Last GHP File Time", 
GHP.S3BUCKET AS "Last GHP File Path",
SUBSTR(HRA.STARTDATE, 6, 2) || '/' ||SUBSTR(HRA.STARTDATE, 9, 2) || '/' ||SUBSTR(HRA.STARTDATE, 1, 4) AS "Auth Start Date",
SUBSTR(HRA.ENDDATE, 6, 2) || '/' ||SUBSTR(HRA.ENDDATE, 9, 2) || '/' ||SUBSTR(HRA.ENDDATE, 1, 4) AS "Auth End Date",
HRA.ENCOUNTERTYPE AS "Encounter Type", 
POS.CODE AS "Place of Service Code", 
POS.NAME AS "Place of Service Name", 
HRA.SELECTEDORDERINGPROVIDER.NAME AS "Ordering Provider Name",  
HRA.SELECTEDORDERINGPROVIDER.NPI AS "Ordering Provider NPI",
HRA.SELECTEDORDERINGPROVIDER.SELECTEDLOCATION.TIN AS "Ordering Provider TIN",
HRA.SELECTEDPERFORMINGPROVIDER.NAME AS "Performing Provider Name",  
HRA.SELECTEDPERFORMINGPROVIDER.NPI AS "Performing Provider NPI",
HRA.SELECTEDPERFORMINGPROVIDER.SELECTEDLOCATION.TIN AS "Performing Provider TIN",
HRA.SELECTEDFACILITY.NAME AS "Facility Name",
HRA.SELECTEDFACILITY.NPI AS "Facility NPI",
HRA.SELECTEDFACILITY.SELECTEDLOCATION.TIN AS "Facility TIN", 
HRA.ISOUTOFNETWORK AS "Out Of Network", 
HRA.URGENCY.ISEXPEDITED AS "Expedited", 
HRA.PRIMARYSEMANTICDIAGNOSISCODE.CODE AS "ICD10CM"
FROM "analytics_dw"."hudi_raw_authorization" HRA
LEFT JOIN (SELECT DISTINCT ID, CODE, NAME
    FROM "analytics_dw"."raw_extract_places_of_service") POS
    ON HRA.placeofservice = POS.ID
LEFT JOIN (SELECT DISTINCT ID, MEMBERID
    FROM "analytics_dw"."raw_extract_patients") PAT
    ON HRA.PATIENT = PAT.ID
LEFT JOIN (SELECT DISTINCT GHP_VENDOR_AUTHORIZATION_NUMBER, MAX(month||'/'||day||'/'||year||'_'||HOUR) AS MAXFILE
    FROM "analytics_dw"."ghp_auth_file_integration_qc"
    GROUP BY GHP_VENDOR_AUTHORIZATION_NUMBER) MAXGHP
    ON HRA.AUTHNUMBER = MAXGHP.GHP_VENDOR_AUTHORIZATION_NUMBER
LEFT JOIN (SELECT DISTINCT GHP_VENDOR_AUTHORIZATION_NUMBER, month||'/'||day||'/'||year||'_'||HOUR AS FILEDATE, "$path" AS S3BUCKET
    FROM "analytics_dw"."ghp_auth_file_integration_qc") GHP
    ON MAXGHP.GHP_VENDOR_AUTHORIZATION_NUMBER = GHP.GHP_VENDOR_AUTHORIZATION_NUMBER AND MAXGHP.MAXFILE = GHP.FILEDATE
WHERE HRA.AUTHSTATUS IN ('APPROVED', 'DENIED', 'PARTIALLY_APPROVED')
AND HRA.HEALTHPLANNAME = 'Geisinger'
AND HRA.DELETED = false
AND HRA.DECISIONTIMESTAMP IS NOT NULL
AND DATE_PARSE(SUBSTR(HRA.DECISIONTIMESTAMP, 1, 10), '%Y-%m-%d') < DATE_ADD('DAY', -2, CURRENT_DATE)
AND (SPLIT_PART(GHP.FILEDATE, '_', 1) < SUBSTR(HRA.DECISIONTIMESTAMP, 6, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 9, 2) || '/' ||SUBSTR(HRA.DECISIONTIMESTAMP, 1, 4) OR MAXGHP.MAXFILE IS NULL)
ORDER BY "Decision Date" ASC;