column_list = '`GHP_assigned_vendor_code`  string , `GHP_vendor_authorization_number`  string , `GHP_record_type`  string , `GHP_request_type`  string , `GHP_subscriber_number`  string , `GHP_member_number`  string , `GHP_type_of_care_indicator`  string , `GHP_service_category`  string , `GHP_service_recieved_date`  string , `GHP_from_or_low_service_date`  string , `GHP_to_or_high_service_date`  string , `GHP_service_group_id`  string , `GHP_procedure_code`  string , `GHP_primary_diagnosis_code`  string , `GHP_units_requested`  string , `GHP_units_authorized`  string , `GHP_units_approved`  string , `GHP_service_status`  string , `GHP_service_deny_date`  string , `GHP_requesting_provider_id`  string , `GHP_servicing_facility_id`  string , `GHP_servicing_facility_name`  string , `GHP_authorized_place_of_service`  string , `GHP_requested_place_of_service`  string , `GHP_servicing_provider_id`  string , `GHP_servicing_provider_full_name`  string , `GHP_servicing_provider_tax_id`  string , `GHP_referring_provider_id`  string , `GHP_referring_provider_full_name`  string , `GHP_referring_provider_tax_id`  string , `GHP_attending_provider_id`  string , `GHP_authorization_type`  string , `GHP_entry_method`  string , `GHP_procedure_code_modifier`  string , `GHP_total_length_of_stay_requested`  string , `GHP_total_length_of_stay_authorized`  string , `GHP_requested_admission_date`  string , `GHP_authorized_admission_date`  string , `GHP_actual_admission_date`  string , `GHP_discharge_expected_date_and_time`  string , `GHP_actual_expected_date_and_time`  string , `GHP_review_date`  string , `GHP_concurrent_reviewed_treatment_type`  string , `GHP_concurrent_reviewed_length_of_stay_requested`  string , `GHP_concurrent_reviewed_length_of_stay_authorized`  string , `GHP_requested_length_of_stay`  string , `GHP_authorized_length_of_stay`  string , `GHP_allowed_days_length_of_stay`  string , `GHP_referral_type`  string , `GHP_service_status_reason`  string , `GHP_auth_hoodie_commit_time`  string , `GHP_additional_notes_line_1`  string , `GHP_additional_notes_line_2`  string , `GHP_additional_notes_line_3`  string , `GHP_additional_notes_line_4`  string , `GHP_additional_notes_line_5`  string , `GHP_additional_notes_line_6`  string , `GHP_additional_notes_line_7`  string , `GHP_is_authorization`  string , `GHP_max_hoodie_commit_time`  Bigint , `GHP_auth_last_updated`  Bigint , `year`  string , `month`  string , `day`  string , `hour`  string'
glue_table = 'analytics_dw.ghp_auth_file_integration_qc'
qc_file_athena_table_key = 's3://cohere-health-external-data/payer/geisinger/auth/outbound/qc/daily/'
spark.sql(f"CREATE EXTERNAL TABLE {glue_table} ({column_list}) PARTITIONED BY (year, month, day, hour) \
        ROW FORMAT SERDE\
      'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' \
        STORED AS INPUTFORMAT \
      'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' \
        OUTPUTFORMAT \
      'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'\
      LOCATION \
      '{qc_file_athena_table_key}'")